[2022-11-05 19:15:30,495] [util.py:209]               [INFO]     |====================================================================================================|
[2022-11-05 19:15:30,496] [plex_meta_manager.py:134]  [INFO]     |                                                                                                    |
[2022-11-05 19:15:30,497] [plex_meta_manager.py:135]  [INFO]     |        ____  _             __  __      _          __  __                                           |
[2022-11-05 19:15:30,497] [plex_meta_manager.py:136]  [INFO]     |       |  _ \| | _____  __ |  \/  | ___| |_ __ _  |  \/  | __ _ _ __   __ _  __ _  ___ _ __         |
[2022-11-05 19:15:30,498] [plex_meta_manager.py:137]  [INFO]     |       | |_) | |/ _ \ \/ / | |\/| |/ _ \ __/ _` | | |\/| |/ _` | '_ \ / _` |/ _` |/ _ \ '__|        |
[2022-11-05 19:15:30,498] [plex_meta_manager.py:138]  [INFO]     |       |  __/| |  __/>  <  | |  | |  __/ || (_| | | |  | | (_| | | | | (_| | (_| |  __/ |           |
[2022-11-05 19:15:30,498] [plex_meta_manager.py:139]  [INFO]     |       |_|   |_|\___/_/\_\ |_|  |_|\___|\__\__,_| |_|  |_|\__,_|_| |_|\__,_|\__, |\___|_|           |
[2022-11-05 19:15:30,498] [plex_meta_manager.py:140]  [INFO]     |                                                                            |___/                   |
[2022-11-05 19:15:30,499] [plex_meta_manager.py:141]  [INFO]     |     Version: 1.15.0                                                                                |
[2022-11-05 19:15:30,499] [util.py:207]               [DEBUG]    |====================================================================================================|
[2022-11-05 19:15:30,499] [plex_meta_manager.py:152]  [DEBUG]    | --config (PMM_CONFIG): None                                                                        |
[2022-11-05 19:15:30,499] [plex_meta_manager.py:153]  [DEBUG]    | --time (PMM_TIME): 03:00                                                                           |
[2022-11-05 19:15:30,499] [plex_meta_manager.py:154]  [DEBUG]    | --run (PMM_RUN): True                                                                              |
[2022-11-05 19:15:30,500] [plex_meta_manager.py:155]  [DEBUG]    | --run-tests (PMM_TEST): False                                                                      |
[2022-11-05 19:15:30,500] [plex_meta_manager.py:156]  [DEBUG]    | --collections-only (PMM_COLLECTIONS_ONLY): False                                                   |
[2022-11-05 19:15:30,500] [plex_meta_manager.py:157]  [DEBUG]    | --libraries-only (PMM_LIBRARIES_ONLY): False                                                       |
[2022-11-05 19:15:30,500] [plex_meta_manager.py:158]  [DEBUG]    | --libraries-first (PMM_LIBRARIES_FIRST): False                                                     |
[2022-11-05 19:15:30,500] [plex_meta_manager.py:159]  [DEBUG]    | --run-collections (PMM_COLLECTIONS): None                                                          |
[2022-11-05 19:15:30,500] [plex_meta_manager.py:160]  [DEBUG]    | --run-libraries (PMM_LIBRARIES): None                                                              |
[2022-11-05 19:15:30,500] [plex_meta_manager.py:161]  [DEBUG]    | --ignore-schedules (PMM_IGNORE_SCHEDULES): False                                                   |
[2022-11-05 19:15:30,501] [plex_meta_manager.py:162]  [DEBUG]    | --delete-collections (PMM_DELETE_COLLECTIONS): False                                               |
[2022-11-05 19:15:30,501] [plex_meta_manager.py:163]  [DEBUG]    | --resume (PMM_RESUME): None                                                                        |
[2022-11-05 19:15:30,501] [plex_meta_manager.py:164]  [DEBUG]    | --no-countdown (PMM_NO_COUNTDOWN): False                                                           |
[2022-11-05 19:15:30,501] [plex_meta_manager.py:165]  [DEBUG]    | --no-missing (PMM_NO_MISSING): False                                                               |
[2022-11-05 19:15:30,501] [plex_meta_manager.py:166]  [DEBUG]    | --read-only-config (PMM_READ_ONLY_CONFIG): False                                                   |
[2022-11-05 19:15:30,501] [plex_meta_manager.py:167]  [DEBUG]    | --divider (PMM_DIVIDER): =                                                                         |
[2022-11-05 19:15:30,502] [plex_meta_manager.py:168]  [DEBUG]    | --width (PMM_WIDTH): 100                                                                           |
[2022-11-05 19:15:30,502] [plex_meta_manager.py:169]  [DEBUG]    | --debug (PMM_DEBUG): False                                                                         |
[2022-11-05 19:15:30,502] [plex_meta_manager.py:170]  [DEBUG]    | --trace (PMM_TRACE): False                                                                         |
[2022-11-05 19:15:30,502] [plex_meta_manager.py:171]  [DEBUG]    |                                                                                                    |
[2022-11-05 19:15:30,502] [util.py:209]               [INFO]     |====================================================================================================|
[2022-11-05 19:15:30,502] [util.py:216]               [INFO]     |                                            Starting Run                                            |
[2022-11-05 19:15:30,503] [util.py:220]               [INFO]     |====================================================================================================|
[2022-11-05 19:15:30,503] [config.py:37]              [INFO]     | Locating config...                                                                                 |
[2022-11-05 19:15:30,503] [config.py:43]              [INFO]     | Using C:\Plex-Stack\Plex-Meta-Manager\config\config.yml as config                                  |
[2022-11-05 19:15:30,538] [util.py:209]               [INFO]     |====================================================================================================|
[2022-11-05 19:15:30,539] [cache.py:17]               [INFO]     | Initializing cache database at C:\Plex-Stack\Plex-Meta-Manager\config\config.cache                 |
[2022-11-05 19:15:30,540] [util.py:209]               [INFO]     |====================================================================================================|
[2022-11-05 19:15:30,541] [config.py:313]             [INFO]     | Connecting to Notifiarr...                                                                         |
[2022-11-05 19:15:30,541] [util.py:162]               [DEBUG]    | Traceback (most recent call last):                                                                 |
                                                                 |   File "C:\Plex-Stack\Plex-Meta-Manager\modules\config.py", line 316, in __init__
                                                                 |     "apikey": check_for_attribute(self.data, "apikey", parent="notifiarr", throw=True),
                                                                 |   File "C:\Plex-Stack\Plex-Meta-Manager\modules\config.py", line 251, in check_for_attribute
                                                                 |     raise Failed(f"Config Error: {message}")
                                                                 | modules.util.Failed: Config Error: notifiarr sub-attribute apikey is blank
                                                                 | 
[2022-11-05 19:15:30,542] [config.py:322]             [ERROR]    | Config Error: notifiarr sub-attribute apikey is blank
[2022-11-05 19:15:30,542] [config.py:323]             [INFO]     | Notifiarr Connection Failed
[2022-11-05 19:15:30,543] [util.py:209]               [INFO]     |====================================================================================================|
[2022-11-05 19:15:30,543] [config.py:341]             [INFO]     | Connecting to TMDb...                                                                              |
[2022-11-05 19:15:30,709] [config.py:346]             [INFO]     | TMDb Connection Successful                                                                         |
[2022-11-05 19:15:30,709] [util.py:209]               [INFO]     |====================================================================================================|
[2022-11-05 19:15:30,710] [config.py:354]             [INFO]     | Connecting to OMDb...                                                                              |
[2022-11-05 19:15:30,710] [config.py:359]             [ERROR]    | Config Error: omdb sub-attribute apikey is blank                                                   |
[2022-11-05 19:15:30,710] [config.py:360]             [INFO]     | OMDb Connection Failed                                                                             |
[2022-11-05 19:15:30,711] [util.py:209]               [INFO]     |====================================================================================================|
[2022-11-05 19:15:30,711] [config.py:368]             [INFO]     | Connecting to Trakt...                                                                             |
[2022-11-05 19:15:30,711] [config.py:378]             [ERROR]    | Config Error: trakt sub-attribute client_id is blank                                               |
[2022-11-05 19:15:30,711] [config.py:379]             [INFO]     | Trakt Connection Failed                                                                            |
[2022-11-05 19:15:30,712] [util.py:209]               [INFO]     |====================================================================================================|
[2022-11-05 19:15:30,712] [config.py:387]             [INFO]     | Connecting to My Anime List...                                                                     |
[2022-11-05 19:15:30,712] [config.py:397]             [ERROR]    | Config Error: mal sub-attribute client_id is blank                                                 |
[2022-11-05 19:15:30,713] [config.py:398]             [INFO]     | My Anime List Connection Failed                                                                    |
[2022-11-05 19:15:30,713] [util.py:209]               [INFO]     |====================================================================================================|
[2022-11-05 19:15:30,713] [config.py:405]             [INFO]     | Connecting to AniDB...                                                                             |
[2022-11-05 19:15:31,357] [config.py:413]             [ERROR]    | AniDB Error: Login failed                                                                          |
[2022-11-05 19:15:31,357] [config.py:414]             [INFO]     | My Anime List Connection Failed Continuing as Guest                                                |
[2022-11-05 19:15:31,358] [util.py:209]               [INFO]     |====================================================================================================|
[2022-11-05 19:15:31,358] [config.py:466]             [WARNING]  | playlist_files attribute not found                                                                 |
[2022-11-05 19:15:31,359] [util.py:209]               [INFO]     |====================================================================================================|
[2022-11-05 19:15:31,360] [config.py:486]             [INFO]     | Connecting to Plex Libraries...                                                                    |
[2022-11-05 19:15:31,360] [util.py:162]               [DEBUG]    | Config Warning: sonarr sub-attribute monitor: False is an invalid input using all as default       |
[2022-11-05 19:15:31,360] [util.py:209]               [INFO]     |====================================================================================================|
[2022-11-05 19:15:31,361] [util.py:216]               [INFO]     |                                        Movies Configuration                                        |
[2022-11-05 19:15:31,361] [util.py:220]               [INFO]     |====================================================================================================|
[2022-11-05 19:15:31,361] [config.py:553]             [INFO]     |                                                                                                    |
[2022-11-05 19:15:31,362] [config.py:554]             [INFO]     | Connecting to Movies Library...                                                                    |
[2022-11-05 19:15:31,362] [util.py:162]               [DEBUG]    | Config Warning: missing_path attribute not found using None as default                             |
[2022-11-05 19:15:31,362] [util.py:162]               [DEBUG]    | Traceback (most recent call last):
                                                                 |   File "C:\Plex-Stack\Plex-Meta-Manager\modules\config.py", line 740, in __init__
                                                                 |     "url": check_for_attribute(lib, "url", parent="plex", var_type="url", default=self.general["plex"]["url"], req_default=True, save=False),
                                                                 |   File "C:\Plex-Stack\Plex-Meta-Manager\modules\config.py", line 241, in check_for_attribute
                                                                 |     raise Failed(f"Config Error: {attribute} attribute must be set under {parent} globally or under this specific Library")
                                                                 | modules.util.Failed: Config Error: url attribute must be set under plex globally or under this specific Library
                                                                 | 
[2022-11-05 19:15:31,363] [util.py:159]               [ERROR]    | Config Error: url attribute must be set under plex globally or under this specific Library
[2022-11-05 19:15:31,363] [config.py:753]             [INFO]     | 
[2022-11-05 19:15:31,364] [config.py:754]             [INFO]     | Movies Library Connection Failed
[2022-11-05 19:15:31,364] [util.py:209]               [INFO]     |====================================================================================================|
[2022-11-05 19:15:31,364] [util.py:216]               [INFO]     |                                        Anime Configuration                                         |
[2022-11-05 19:15:31,365] [util.py:220]               [INFO]     |====================================================================================================|
[2022-11-05 19:15:31,365] [config.py:553]             [INFO]     |                                                                                                    |
[2022-11-05 19:15:31,365] [config.py:554]             [INFO]     | Connecting to Anime Library...                                                                     |
[2022-11-05 19:15:31,365] [util.py:162]               [DEBUG]    | Config Warning: missing_path attribute not found using None as default                             |
[2022-11-05 19:15:31,366] [util.py:162]               [DEBUG]    | Traceback (most recent call last):
                                                                 |   File "C:\Plex-Stack\Plex-Meta-Manager\modules\config.py", line 740, in __init__
                                                                 |     "url": check_for_attribute(lib, "url", parent="plex", var_type="url", default=self.general["plex"]["url"], req_default=True, save=False),
                                                                 |   File "C:\Plex-Stack\Plex-Meta-Manager\modules\config.py", line 241, in check_for_attribute
                                                                 |     raise Failed(f"Config Error: {attribute} attribute must be set under {parent} globally or under this specific Library")
                                                                 | modules.util.Failed: Config Error: url attribute must be set under plex globally or under this specific Library
                                                                 | 
[2022-11-05 19:15:31,367] [util.py:159]               [ERROR]    | Config Error: url attribute must be set under plex globally or under this specific Library
[2022-11-05 19:15:31,367] [config.py:753]             [INFO]     | 
[2022-11-05 19:15:31,367] [config.py:754]             [INFO]     | Anime Library Connection Failed
[2022-11-05 19:15:31,367] [util.py:209]               [INFO]     |====================================================================================================|
[2022-11-05 19:15:31,368] [util.py:162]               [DEBUG]    | Traceback (most recent call last):                                                                 |
                                                                 |   File "C:\Plex-Stack\Plex-Meta-Manager\plex_meta_manager.py", line 176, in start
                                                                 |     config = ConfigFile(default_dir, attrs, read_only_config)
                                                                 |   File "C:\Plex-Stack\Plex-Meta-Manager\modules\config.py", line 844, in __init__
                                                                 |     raise Failed("Plex Error: No Plex libraries were connected to")
                                                                 | modules.util.Failed: Plex Error: No Plex libraries were connected to
                                                                 | 
[2022-11-05 19:15:31,369] [util.py:158]               [CRITICAL] | Plex Error: No Plex libraries were connected to
[2022-11-05 19:15:31,370] [plex_meta_manager.py:190]  [INFO]     | 
[2022-11-05 19:15:31,370] [util.py:209]               [INFO]     |====================================================================================================|
[2022-11-05 19:15:31,371] [util.py:216]               [INFO]     |                                            Finished Run                                            |
[2022-11-05 19:15:31,371] [util.py:216]               [INFO]     |                          Finished: 19:15:31 2022-11-05 Run Time: 0:00:00                           |
[2022-11-05 19:15:31,371] [util.py:220]               [INFO]     |====================================================================================================|
